spring.application.name=aws_ai_chatbot
# Force servlet web app (start Tomcat) instead of serverless adapter
spring.main.web-application-type=servlet

# Server
server.port=8080

# AWS Bedrock (region + model)
app.bedrock.model-id=us.anthropic.claude-sonnet-4-20250514-v1:0
app.bedrock.region=us-east-1

# MVC async (SSE) do not time out
spring.mvc.async.request-timeout=0
